### ISSUE TITLE
Create subdirectories in the calculus folder

### ISSUE THREAD

**Issue by pi3d-p1p3r** [AppliedMathematicsProgrammingSociety/amps#4]
Your code plotting tangent lines is directly under the calculus directory. As other code will be uploaded, either put it under the subdirectory of plotting graphs or create a new one named plotting tangent from graphs.

![image](https://user-images.githubusercontent.com/111991013/224227632-f30cab2c-7f3f-4b77-a374-c875263f8696.png)

**Comment by yakeen15** [comment]
issue is resolved, created a new folder named plot tangent to curve
